Traceback (most recent call last):
  File "c:\users\jouko\appdata\local\programs\python\python39\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\users\jouko\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\jouko\appdata\local\programs\python\python39\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\jouko\appdata\local\programs\python\python39\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\jouko\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\users\jouko\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "c:\users\jouko\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\jouko\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# shared imports 
from myst_nb import glue
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 12 * np.pi, 200)
y = np.sin(x)+np.sin(2*x)

fig, ax = plt.subplots()
ax.plot(x, y)
plt.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_5228/619627048.py[0m in [0;36m<module>[1;34m[0m
[0;32m      2[0m [1;32mfrom[0m [0mmyst_nb[0m [1;32mimport[0m [0mglue[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [1;32mimport[0m [0mnumpy[0m [1;32mas[0m [0mnp[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 4[1;33m [1;32mimport[0m [0mmatplotlib[0m[1;33m.[0m[0mpyplot[0m [1;32mas[0m [0mplt[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      5[0m [1;33m[0m[0m
[0;32m      6[0m [0mx[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0mlinspace[0m[1;33m([0m[1;36m0[0m[1;33m,[0m [1;36m12[0m [1;33m*[0m [0mnp[0m[1;33m.[0m[0mpi[0m[1;33m,[0m [1;36m200[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'matplotlib'
ModuleNotFoundError: No module named 'matplotlib'

